# Generated by Django 4.2.3 on 2023-07-20 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('SAV', 'Savings'), ('CUR', 'Current')], max_length=4)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('PAU', 'Paused'), ('DEL', 'Deleted')], default='ACT', max_length=4)),
                ('branch', models.CharField(max_length=255)),
                ('facility', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ifsc', models.CharField(max_length=11, unique=True)),
                ('od_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('drawing_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('micr_code', models.CharField(max_length=9)),
                ('masked_account_no', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('DEB', 'Debit'), ('CRE', 'Credit')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode', models.CharField(choices=[('UPI', 'UPI'), ('NEF', 'NEFT'), ('RTG', 'RTGS'), ('CRE', 'Credit Card'), ('DEB', 'Debit Card')], default='UPI', max_length=3)),
                ('imgurl', models.URLField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Others', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('goal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('goal_url', models.URLField(blank=True, null=True)),
                ('recurrence', models.CharField(blank=True, choices=[('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly')], max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
