# Generated by Django 4.2.3 on 2023-07-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_goal_url_alter_transaction_imgurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='goal_url',
            new_name='goal_img',
        ),
    ]
