# Generated by Django 4.2.3 on 2023-07-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_imgurl_transaction_bill_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bill_img',
            new_name='billimg',
        ),
    ]
