# Generated by Django 4.2.3 on 2023-07-21 15:07

import budget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_delete_ocr_transaction_bill_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=budget.models.upload_img_ocr_path_handler)),
            ],
        ),
    ]
