# Generated by Django 4.2.3 on 2023-07-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_ocr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=255, unique=True)),
                ('discount', models.IntegerField(default=10)),
                ('expiry_date', models.DateField()),
                ('value_points', models.IntegerField(default=100)),
            ],
        ),
    ]
