# Generated by Django 4.2.3 on 2023-07-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Shopping', 'Shopping'), ('Transport', 'Transport')], default='Food', max_length=255),
        ),
        migrations.AddField(
            model_name='coupons',
            name='name',
            field=models.CharField(default='Coupon', max_length=255),
        ),
    ]
