# Generated by Django 4.2.3 on 2023-07-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_coupons_category_coupons_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='current_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Shopping', 'Shopping'), ('Transport', 'Transport')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('NEF', 'NEFT'), ('RTG', 'RTGS'), ('CRE', 'Credit Card'), ('DEB', 'Debit Card'), ('OTH', 'Others')], default='UPI', max_length=3),
        ),
    ]
