name: financeguru
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  skeletons: ^0.0.3
  percent_indicator: ^4.2.3
  intl: ^0.18.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  introduction_screen: ^3.1.8
  get_storage: ^2.1.1
  lottie: ^2.4.0
  flutter_overlay_loader: ^2.0.0
  image_picker: ^1.0.1
  file_picker: ^5.3.2
  razorpay_flutter: ^1.3.5
  dotted_border: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bibit.jpg
    - assets/images/gopay.jpg
    - assets/images/profile.jpg
    - assets/images/chip.png
    - assets/json/
    - assets/json/saving_target_dummy.json
    - assets/json/transaction_dummy.json
    - assets/json/credit_card_dummy.json
    - assets/json/pocket_dummy.json