# Generated by Django 4.2.3 on 2023-07-21 05:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_img_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gov_id_url',
        ),
        migrations.AddField(
            model_name='user',
            name='card_img',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_card_path_handler),
        ),
        migrations.AddField(
            model_name='user',
            name='gov_id_img',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_gov_path_handler),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepicurl',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=accounts.models.upload_path_handler),
        ),
    ]
