# Generated by Django 4.2.3 on 2023-07-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_card_img_url_remove_user_gov_id_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profilepicurl',
            new_name='profilepic',
        ),
    ]
