# Generated by Django 4.2.3 on 2023-07-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
